language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - py.test tests/fizzbuzztest.py
  - coverage report -m tests/fizzbuzztest.py
after_success:
  - coveralls
  - pytest