language: python
python:
  - "3.6"
install:
  - pip install -r requirments.txt
script:
  - py.test --cov-config .converagerc --cov=app tests/
  - coverage report
after_success:
  - coveralls
  - pytest